In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
city_data = pd.read_csv("Resources/city_pop_transit_age_latlng.csv")
city_data.head()

,City,Population,Public Transportation Rate,Median Age,Lat,Lng
0,ABAC,25590.0,0.346470,36.90,31.483076,-83.530194
1,Aberdeen,31027.0,0.362211,36.70,57.149717,-2.094278
2,Aberdeen Township,30709.0,11.924538,41.70,40.417095,-74.222116
3,Abilene,57336.0,0.802012,31.45,32.448736,-99.733144
4,Abingdon,29587.0,1.981002,35.60,36.709833,-81.977348

In [7]:
low_transportation = city_data.loc[city_data["Public Transportation Rate"] > .5]
low_transportation = low_transportation.sort_values("Public Transportation Rate")
low_transportation.head(20)

,City,Population,Public Transportation Rate,Median Age,Lat,Lng
1057,Lenexa,101632.0,0.500354,36.75,38.953617,-94.733571
1989,Texarkana,72268.0,0.501404,37.05,33.425125,-94.047688
2142,Wausau,30896.0,0.501759,38.80,44.959135,-89.630122
2259,Yucca Valley,25045.0,0.502043,39.40,34.114174,-116.432235
2074,Valrico,63805.0,0.503619,39.75,27.946261,-82.242032
1041,Laveen Village,39137.0,0.503644,28.90,33.362823,-112.169317
380,Coeur d'Alene,57152.0,0.506058,39.15,47.673463,-116.781223
2039,Twin Falls,53582.0,0.507529,33.50,42.555838,-114.470052
121,Battle Creek,26055.0,0.508842,40.70,42.321152,-85.179714
85,Atwater,38007.0,0.511394,32.80,37.347717,-120.609084
1893,Southington,32644.0,0.512759,44.10,41.596487,-72.877601
2186,Westerville,88241.0,0.513851,38.35,40.126669,-82.931881
739,Grand Haven,30147.0,0.514333,39.70,43.063073,-86.228386
1696,Roanoke,126550.0,0.515691,40.55,35.889743,-75.661538
1977,Taycheedah,42260.0,0.515715,38.30,43.808878,-88.395106
311,Ca√±on City,30211.0,0.518191,43.20,38.449406,-105.225332
524,East Gull Lake,29469.0,0.520098,39.00,46.408023,-94.355835
1290,Morovis,32484.0,0.521989,34.30,18.325785,-66.406559
1331,Naranjito,30772.0,0.522438,36.40,18.300786,-66.244890
442,Dalton,81340.0,0.525290,34.35,34.769802,-84.970223

In [8]:
low_transportation = low_transportation.loc[low_transportation["Population"] >= 50000]
low_transportation.head(20)

,City,Population,Public Transportation Rate,Median Age,Lat,Lng
1057,Lenexa,101632.0,0.500354,36.750000,38.953617,-94.733571
1989,Texarkana,72268.0,0.501404,37.050000,33.425125,-94.047688
2074,Valrico,63805.0,0.503619,39.750000,27.946261,-82.242032
380,Coeur d'Alene,57152.0,0.506058,39.150000,47.673463,-116.781223
2039,Twin Falls,53582.0,0.507529,33.500000,42.555838,-114.470052
2186,Westerville,88241.0,0.513851,38.350000,40.126669,-82.931881
1696,Roanoke,126550.0,0.515691,40.550000,35.889743,-75.661538
442,Dalton,81340.0,0.525290,34.350000,34.769802,-84.970223
1714,Rome,117074.0,0.528653,39.566667,41.902784,12.496365
1754,Salinas,150854.0,0.529679,30.833333,36.677737,-121.655501
2053,Uniontown,58720.0,0.530892,43.550000,39.900076,-79.716433
1300,Mount Pleasant,155242.0,0.535140,33.125000,32.832322,-79.828426
820,Helena,54833.0,0.540566,41.500000,38.979416,-94.856688
623,Far West Side,54898.0,0.543306,30.400000,29.494035,-98.704767
789,Hadley,57296.0,0.544330,28.300000,42.341757,-72.588422
514,Eagle Pass,54447.0,0.548503,29.400000,28.709143,-100.499521
2018,Traverse City,71543.0,0.549138,43.450000,44.763057,-85.620632
318,Centerville,52929.0,0.550273,47.600000,39.628393,-84.159382
1856,Snellville,76797.0,0.553517,36.900000,33.857328,-84.019911
1093,Lodi,73484.0,0.561381,37.050000,38.134148,-121.272219

In [11]:
low_trans_rate = low_transportation.loc[low_transportation["Public Transportation Rate"] < 1]
low_trans_rate.head(30)

,City,Population,Public Transportation Rate,Median Age,Lat,Lng
1057,Lenexa,101632.0,0.500354,36.750000,38.953617,-94.733571
1989,Texarkana,72268.0,0.501404,37.050000,33.425125,-94.047688
2074,Valrico,63805.0,0.503619,39.750000,27.946261,-82.242032
380,Coeur d'Alene,57152.0,0.506058,39.150000,47.673463,-116.781223
2039,Twin Falls,53582.0,0.507529,33.500000,42.555838,-114.470052
2186,Westerville,88241.0,0.513851,38.350000,40.126669,-82.931881
1696,Roanoke,126550.0,0.515691,40.550000,35.889743,-75.661538
442,Dalton,81340.0,0.525290,34.350000,34.769802,-84.970223
1714,Rome,117074.0,0.528653,39.566667,41.902784,12.496365
1754,Salinas,150854.0,0.529679,30.833333,36.677737,-121.655501
2053,Uniontown,58720.0,0.530892,43.550000,39.900076,-79.716433
1300,Mount Pleasant,155242.0,0.535140,33.125000,32.832322,-79.828426
820,Helena,54833.0,0.540566,41.500000,38.979416,-94.856688
623,Far West Side,54898.0,0.543306,30.400000,29.494035,-98.704767
789,Hadley,57296.0,0.544330,28.300000,42.341757,-72.588422
514,Eagle Pass,54447.0,0.548503,29.400000,28.709143,-100.499521
2018,Traverse City,71543.0,0.549138,43.450000,44.763057,-85.620632
318,Centerville,52929.0,0.550273,47.600000,39.628393,-84.159382
1856,Snellville,76797.0,0.553517,36.900000,33.857328,-84.019911
1093,Lodi,73484.0,0.561381,37.050000,38.134148,-121.272219
1019,Lakeland,170570.0,0.561873,40.780000,42.306742,-82.865163
469,Delano,56028.0,0.562463,29.100000,36.090034,-115.177580
291,Cape Coral,99262.0,0.563913,47.233333,26.562854,-81.949533
812,Hattiesburg,85450.0,0.564808,31.250000,31.327119,-89.290339
2202,Wichita,157918.0,0.565502,33.200000,37.687176,-97.330053
1565,Pflugerville,77046.0,0.572568,33.700000,30.454845,-97.622267
128,Baytown,53091.0,0.573093,31.500000,29.735505,-94.977427
194,Boise,180848.0,0.574104,34.560000,43.615019,-116.202314
704,Gastonia,103941.0,0.574158,37.500000,35.262082,-81.187300
742,Grand Prairie,173976.0,0.574244,31.200000,32.745964,-96.997785

In [12]:
low_trans_rate.to_csv("Resources/low_rate.csv", index=False)